# cloudbuild.yaml
steps:
# 1. Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build-Image
  args:
    [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/pdf-summarizer-ai:$COMMIT_SHA',
      '.',
    ]

# 2. Push the Docker image to Google Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  id: Push-Image
  args: ['push', 'gcr.io/$PROJECT_ID/pdf-summarizer-ai:$COMMIT_SHA']

# ----------------------------------------------------------------------
# FIX for the "Failed to trigger build" error
# ----------------------------------------------------------------------
# Using your provided custom service account email:
serviceAccount: 'projects/${_PROJECT_ID}/serviceAccounts/pdf-summarizer-sa@diesel-practice-470815-u1.iam.gserviceaccount.com'
options:
  # This tells Cloud Build to send logs to Cloud Logging only, satisfying the requirement
  logging: CLOUD_LOGGING_ONLY

# ----------------------------------------------------------------------
# Define the images to be created for tracking in the console
# ----------------------------------------------------------------------
images:
  - 'gcr.io/$PROJECT_ID/pdf-summarizer-ai:$COMMIT_SHA'

# ----------------------------------------------------------------------
# Optional: Deploy to Cloud Run after a successful build
# ----------------------------------------------------------------------
# Uncomment and customize the following section to enable automatic deployment.
# - name: 'gcr.io/cloud-builders/gcloud'
#   id: Deploy-to-Cloud-Run
#   args:
#     [
#       'run',
#       'deploy',
#       'pdf-summarizer-ai',
#       '--image',
#       'gcr.io/$PROJECT_ID/pdf-summarizer-ai:$COMMIT_SHA',
#       '--region',
#       'us-central1',  # ⬅️ IMPORTANT: Change this to your desired region!
#       '--platform',
#       'managed',
#       '--allow-unauthenticated' # Use '--no-allow-unauthenticated' for a private service
#     ]
